### ISSUE TITLE
Job tracking and Slurm interaction

### ISSUE THREAD

**Issue by winni2k** [winni2k/snakemake-mini-hackathon-2019#2]
This is a stub for a work item mentioned in #1.

**Comment by winni2k** [comment]
This might be relevant https://bitbucket.org/snakemake/snakemake/pull-requests/348

**Comment by boulund** [comment]
Identified three subcomponents to this:

- [ ] Create minimal working example
  - [ ] Create reproducible environment for minimal working example
- [ ] Understand how Ctrl-C is handled by Snakemake
- [ ] How does Snakemake keep track of submitted/running jobs?
